# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('adoption_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.AdoptionProposal')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_location', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('dni', models.CharField(max_length=8)),
                ('born_date', models.DateField()),
                ('phone_number', models.CharField(max_length=18)),
                ('status', models.CharField(choices=[('Desconectado', 'Desconectado'), ('Conectado', 'Conectado'), ('Bloqueado', 'Bloqueado')], default='Desconectado', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Person'),
        ),
        migrations.AddField(
            model_name='animalreport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Location'),
        ),
        migrations.AddField(
            model_name='animalreport',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Person'),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='start.Person'),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='start.Person'),
        ),
    ]
