# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_personimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/reports/pets')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.AnimalReport')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='adoption_proposal',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
