# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-20 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_auto_20171020_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(default='', max_length=180),
        ),
    ]
