# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-21 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0007_auto_20171020_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='place',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start.Place'),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='start.Place'),
        ),
    ]
