# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_auto_20171021_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/adoptions/pets')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_device', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='adoptionproposal',
            name='person_give',
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='start.Person'),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoptionproposal',
            name='was_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animalreport',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoptionimage',
            name='adoption_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.AdoptionProposal'),
        ),
    ]
