# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_auto_20171028_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionproposal',
            name='pet_name',
            field=models.CharField(blank=True, default='Sin nombre', max_length=50, null=True),
        ),
    ]
